version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/node:10
      - image: circleci/redis:4-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Build
          command: npm run build
      - run:
          name: Build docs
          command: npm run typedoc
      - persist_to_workspace:
          root: .
          paths:
            - docs
            - lib

  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: npm publish

  docs-deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: docs
      - run:
          name: Install and configure dependencies
          command: |
            npm install gh-pages@2.1.1
            git config user.email "ci-build@escale.com.br"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: ./node_modules/.bin/gh-pages --dist docs

ci_only: &ci_only
  filters:
    branches:
      ignore: gh-pages
    tags:
      ignore: /.*/

release_only: &release_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v.*/

workflows:
  version: 2
  ci:
    jobs:
      - build-and-test:
          <<: *ci_only
  release:
    jobs:
      - build-and-test:
          <<: *release_only
      - deploy:
          <<: *release_only
          requires:
            - build-and-test
      - docs-deploy:
          <<: *release_only
          requires:
            - build-and-test
